### ISSUE TITLE
sqlite3.OperationalError: attempt to write a readonly database

### ISSUE THREAD

**Issue by michzimny** [sciencemesh/cs3api4lab#28]
From time to time, I get the following error when working on a `*.ipynb` file backed by the plugin:

```
[I 2020-11-17 09:42:55.083 SingleUserLabApp cs3_file_api:110] msg="File open for read" filepath="/Untitled.ipynb" elapsedTimems="9.6"
[E 2020-11-17 09:42:55.086 SingleUserLabApp web:1788] Uncaught exception GET /user/test/api/contents/Untitled.ipynb?type=notebook&content=1&1605606175056 (192.168.65.3)
    HTTPServerRequest(protocol='http', host='localhost', method='GET', uri='/user/test/api/contents/Untitled.ipynb?type=notebook&content=1&1605606175056', version='HTTP/1.1', remote_ip='192.168.65.3')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
        yielded = next(result)
      File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 112, in get
        path=path, type=type, format=format, content=content,
      File "/opt/cs3/cs3api4lab/api/cs3apismanager.py", line 95, in get
        model = self._notebook_model(path, content=content)
      File "/opt/cs3/cs3api4lab/api/cs3apismanager.py", line 296, in _notebook_model
        self.mark_trusted_cells(nb, path)
      File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 508, in mark_trusted_cells
        trusted = self.notary.check_signature(nb)
      File "/opt/conda/lib/python3.7/site-packages/nbformat/sign.py", line 439, in check_signature
        return self.store.check_signature(signature, self.algorithm)
      File "/opt/conda/lib/python3.7/site-packages/nbformat/sign.py", line 239, in check_signature
        (datetime.utcnow(), algorithm, digest),
    sqlite3.OperationalError: attempt to write a readonly database
```

Unfortunately, I don't know how to reproduce it. The problem stops (for some time) when I restart the jupyterlab container.

My environment:
- reva 1.3.0
- cs3api4lab in the Zero to JupyterHub setup, in minikube, see config below (because of #25, I removed the two problematic lines from the Dockerfile, to be able to build the image)

Zero to JupyterHub config:
```
proxy:
  secretToken: 41cbb7e6ba54a65a87aa1ae75c075dff62034db0c9fc01275e0f57c82e190d7b
  https:
    enabled: false

singleuser:
  image:
    name: michzimny/cs3api4lab-jupyterlab
    tag: branch-hotfix-master
    pullPolicy: Always
  defaultUrl: "/lab"
  extraEnv:
    CS3_EXT_CONFIG: "true"
    CS3_REVA_HOST: "172.19.0.1:19000"
    CS3_AUTH_TOKEN_VALIDITY: "3600"
    CS3_HOME_DIR: "/home"
    CS3_ENDPOINT: /
    CS3_CHUNK_SIZE: "4194304"
    CS3_SECURE_CHANNEL: "false"
    CS3_CLIENT_CERT: ""
    CS3_CLIENT_KEY: ""
    CS3_CA_CERT: ""
    CS3_CLIENT_ID: "einstein"
    CS3_CLIENT_SECRET: "relativity"
    CS3_LOGIN_TYPE: "basic"
```

**Comment by diocas** [comment]
I'm not sure this is a problem with our extension.. When you execute or trust a notebook, this information is stored in a db which, unless you set `NotebookNotary.db_file`, should live inside the user home folder. This is what is failing. 
But it also means that the DB lives in the local filesystem so is completely independent from the extension and REVA. 

Are you using your sync client as well? Or does the home have some other special configuration?

**Comment by michzimny** [comment]
Thank you. This may be related to my current setup that reva files are read-only.
